name: Terraform validate

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setting up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform-version: latest

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform changes
        run: terraform validat
